name: Build and push CUDA 12.4 docker image

on:
  push:
    branches: ["release"]
    paths:
      - "Dockerfile"
      - "scripts/**"
      - "src/**"
      - "pyproject.toml"
  pull_request:
    branches: ["release"]
    paths:
      - "Dockerfile"
      - "scripts/**"
      - "src/**"
      - "pyproject.toml"

env:
  REGISTRY: ghcr.io

jobs:
  build-push-cuda12-4:
    if: "!contains(github.event.head_commit.message, '[no-ci]')"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert repository name to lowercase
        run: echo "IMAGE_NAME=$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cuda12-4
          build-args: BASE_IMAGE=nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04
          #          cache-from: type=gha
          #          cache-to: type=gha,mode=max
